src/Entity/SubMenus.php
<?php

namespace App\Entity;

use App\Repository\SubMenusRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SubMenusRepository::class)]
class SubMenus
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(nullable: true)]
    private ?int $submenuOrder = null;

    #[ORM\Column]
    private ?bool $is_visible = null;

    #[ORM\Column(length: 255)]
    private ?string $link = null;

    #[ORM\ManyToOne(targetEntity: Menu::class, inversedBy: 'subMenuses', cascade: ["persist", "remove"])]
    #[ORM\JoinColumn(name: 'menu_id', referencedColumnName: 'id')]
    private ?Menu $menu = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSubmenuOrder(): ?int
    {
        return $this->submenuOrder;
    }

    public function setSubmenuOrder(?int $submenuOrder): static
    {
        $this->submenuOrder = $submenuOrder;

        return $this;
    }

    public function isIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): static
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): static
    {
        $this->link = $link;

        return $this;
    }

    public function getMenu(): ?Menu
    {
        return $this->menu;
    }

    public function setMenu(?Menu $menu): static
    {
        $this->menu = $menu;

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }
}

templates/header/nav.html.twig
<div class="container">
	<input type="checkbox" name="check" id="check"/>
	<div class="logo-container">
		{# <a href="/"><img class="logoBada" src="uploads/logo-bada-437d061c-b6dc-4077-a8c3-42ae8d8f322b.avif" alt=""></a> #}
		<a class="logo" href="127.0.0.1:8000/" alt="Badaboum theatre">Badaboum<span>THÉÂTRE</span></a>
	</div>
	<div class="nav-btn">
		<ul class="nav-links">
				{% for menu in menus %}
					{% if menu.isVisible == 1 %}
						<li class="nav-link">
							<a href="
								{{ menu.link }}
								">{{ menu.name|capitalize }}</a>
							{% if menu.subMenuses is not empty %}
								<div class="dropdown">
									<ul>
										{% for subMenu in menu.subMenuses %}
											{% if subMenu.isVisible == 1 %}
												<li class="dropdown-link">
													<a href="
														{{ subMenu.link }}
														">{{ subMenu.name|capitalize }}</a>
												</li>
												<div class="arrow"></div>
											{% endif %}
										{% endfor %}
									</ul>
								{% endif %}
							</li>
						{% endif %}
					{% endfor %}
				</ul>
			</ul>
		</div>
		<div class="hamburger-menu-container">
			<div class="hamburger-menu">
				<div></div>
			</div>
		</div>
	</div>
	{% if is_granted('IS_AUTHENTICATED_FULLY') %}
		<a class="dashboard" href="{{path('admin')}}">Tableau de bord</a>
	{% endif %}

	{# NEWSLETTER #}
	{# <button id="btnNewsletter" class="logoNewsletter">N</button>
	<form action="" class="formNewsletter"></form> #}